version: '3'

services:
  app:
    build: 
     context: .
     dockerfile: Dockerfile
    ports:
    - "3000-3000"
    depends_on:
      - db
    env_file:
      - .env
    command: npm start
  
  db: 
    image: postgres:13-alpine
    ports:
    - "5432:5432"
    volumes:
    - ./prisma:/app/prisma
    environment:
    - POSTGRES_DB=book-db
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=Hie Yaar

  